import type { Metadata } from "next";
import "./globals.css";
import Layout from "./UI/Layout";
import localFont from "next/font/local";

const MSSansSerif = localFont({ src: "../public/fonts/MS_Sans_Serif.ttf" });
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${MSSansSerif.className} h-full w-full antialiased tracking-wider`}
      suppressHydrationWarning
    >
      <body className="h-full flex">
        <div className="flex w-full relative">
          <Layout>{children}</Layout>
        </div>
      </body>
    </html>
  );
}
